AUTHOR = 'antoine'
PKG_NAME = 'try1'
VERSION = '1.0.0'
EMAIL = ''
DEFAULT_FILE = ''
PACKAGE = ['requests', 'requests', 'requests', 'django', 'django', 'django', 'django', 'requests', 'pandas', 'django', 'django', 'django', 'requests', 'django', 'pandas']
LIST_FILE = []
DESCRIPTION = ''
GIT_REPO = ''
PWD = '/Users/antoine/Documents/pykg/trying'